export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',

  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_DISSOLVED = 'ROOM_DISSOLVED',
  JOIN_CODE_INVALID = 'JOIN_CODE_INVALID',
  NOT_A_MEMBER = 'NOT_A_MEMBER',
  MEMBER_BANNED = 'MEMBER_BANNED',

  MEETING_NOT_FOUND = 'MEETING_NOT_FOUND',
  MEETING_ALREADY_ENDED = 'MEETING_ALREADY_ENDED',
  MEETING_ALREADY_ACTIVE = 'MEETING_ALREADY_ACTIVE',

  WHITEBOARD_LIMIT_EXCEEDED = 'WHITEBOARD_LIMIT_EXCEEDED',
  AI_GENERATION_FAILED = 'AI_GENERATION_FAILED',
  AI_RATE_LIMITED = 'AI_RATE_LIMITED',

  IMPORT_FILE_INVALID = 'IMPORT_FILE_INVALID',
  IMPORT_TOO_MANY_ROWS = 'IMPORT_TOO_MANY_ROWS',
}

export interface ApiErrorBody {
  statusCode: number;
  error: ErrorCode;
  message: string;
  details?: Array<{ field: string; constraint: string }>;
}
